CREATE TABLE AUTHOR(ID NUMBER,AUTHORNAME VARCHAR(40),SEX VARCHAR(1),PRIMARY KEY (AUTHORNAME));

CREATE TABLE BOOK (ISBN VARCHAR(10), AUTHOR_NAME VARCHAR(40),TITLE VARCHAR(100), PRIMARY KEY (ISBN),FOREIGN KEY (AUTHOR_NAME) REFERENCES AUTHOR(AUTHORNAME));

INSERT INTO AUTHOR values (1,'A1','M');
INSERT INTO BOOK values ('A1234','A1','T1');